version: '3'

volumes:
  nextcloud_html:
    driver: local
  nextcloud_db:
    driver: local
  letsencrypt_data:
    driver: local
  document_data:
    driver: local
  document_log:
    driver: local

services:
  db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root

  nextcloud:
    image: nextcloud:latest
    expose:
      - '80'
    volumes:
      - nextcloud_html:/var/www/html
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    depends_on:
      - db

  swag:
    image: linuxserver/swag:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt_data:/config
      - ./nginx.cfg:/config/nginx/site-confs/default:ro
    restart: unless-stopped
    environment:
      - PUID=1050
      - PGID=1050
      - EMAIL=
      - URL=
      - SUBDOMAINS=cloud,office
      - TZ=Europe/Berlin
      - ONLY_SUBDOMAINS=true
    depends_on:
      - nextcloud
      - onlyoffice
      - cron

  onlyoffice:
    image: onlyoffice/documentserver:latest
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    depends_on:
      - nextcloud

  cron:
    image: tigpt/cronjobs
    volumes:
      - ./crontab_root:/etc/crontabs/root
    restart: unless-stopped
    depends_on:
      - nextcloud

